integrating all logging/syntax improvements from decode_OH (now decode_include) in the decode template. The decode template and the decode_include are now very similar and the only level of duplication left.

diff --git a/local/decode_template b/local/decode_template
--- a/local/decode_template
+++ b/local/decode_template
@@ -3,6 +3,7 @@
 
 #
 # Author: Laurens van der Werff (University of Twente)
+#         >2020 (heavily adapted by Maarten van Gompel (CLST, Radboud University Nijmegen))
 #
 # Apache 2.0
 #
@@ -44,33 +45,49 @@
 #			found in <output-dir>/1Best.ctm.{dtl,pra,sys}
 #
 
+#auto export all variables
 set -a
 
-cmd=run.pl
-nj=4                    # maximum number of simultaneous jobs used for feature generation and decoding
-stage=1
-numthreads=1           # used for decoding
+die() {
+	echo "-------------------------------------------------" >&2
+    echo "ERROR: $*" >&2
+	echo "-------------------------------------------------" >&2
+	[ -z "$logging" ] || echo "(you can inspect the log at $logging for details)" >&2
+    exit 2
+}
 
-file_types="wav mp3"			# file types to include for transcription
-splittext=true
-json=false
-dorescore=true			# rescore with largeLM as default
-copyall=false			# copy all source files (true) or use symlinks (false)
-overwrite=true			# overwrite the 1st pass output if already present
-multichannel=false
-inv_acoustic_scale="11"    # used for 1-best and N-best generation
-nbest=0					  # if value >0, generate NBest.ctm with this amount of transcription alternatives
-word_ins_penalty="-1.0"   # word insertion penalty
-beam=11
-decode_mbr=true
-miac=
-mwip=
+[ -n "$cmd" ] && cmd="run.pl"
+[ -n "$nj" ] && nj=8                               # maximum number of simultaneous jobs used for feature generation and decoding
+[ -n "$stage" ] && stage=1
+[ -n "$numthreads" ] && numthreads=1               # used for decoding
+[ -n "$file_types" ] && file_types="wav mp3"       # file types to include for transcription
+[ -n "$splittext" ] && splittext=true
+[ -n "$dorescore" ] && dorescore=true              # rescore with largeLM as default
+[ -n "$copyall" ] && copyall=false                 # copy all source files (true) or use symlinks (false)
+[ -n "$overwrite" ] && overwrite=true              # overwrite the 1st pass output if already present
+[ -n "$multichannel" ] && multichannel=true
+[ -n "$nbest" ] && nbest=0                         # if value >0, generate NBest.ctm with this amount of transcription alternatives
+[ -n "$inv_acoustic_scale" ] && inv_acoustic_scale="11"  # used for 1-best and N-best generation
+[ -n "$word_ins_penalty" ] && word_ins_penalty="-1.0" # word insertion penalty
+[ -n "$beam" ] && beam=11
+[ -n "$decode_mbr" ] && decode_mbr=true
+
+
 
 **** INSERT DECODE_OPTIONS ****
 
-symtab=$lpath/words.txt
-wordbound=$lpath/phones/word_boundary.int
-[ "$llpath" ] && symtab=$llpath/words.txt && wordbound=$llpath/phones/word_boundary.int
+
+[ -n "$model" ] && die "This script must be sourced, missing: \$model"
+[ -n "$graph" ] && graph="$model/graph"
+[ -n "$lmodel" ] && die "This script must be sourced, missing: \$lmodel"
+[ -n "$lpath" ] && die "This script must be sourced, missing: \$lpath"
+[ -n "$llpath" ] && die "This script must be sourced, missing: \$llpath"
+[ -n "$symtab" ] && die "This script must be sourced, missing: \$symtab"
+[ -n "$wordbound" ] && die "This script must be sourced, missing: \$wordbound"
+
+symtab="$lpath/words.txt"
+wordbound="$lpath/phones/word_boundary.int"
+[ -e "$llpath" ] && symtab="$llpath/words.txt" && wordbound="$llpath/phones/word_boundary.int"
 
 [ -f ./path.sh ] && . ./path.sh; # source the path.
 
@@ -98,76 +115,88 @@ if [ $# -lt 2 ]; then
 fi
 
 result=${!#}
+if [[ "$model" = *" "* ]]; then
+	die "Model path ($model) may not contain any spaces!"
+fi
+if [[ "$result" = *" "* ]]; then
+	die "Output path ($result) may not contain any spaces!"
+fi
 inter="${result}/intermediate"
 data="${inter}/data"
 logging="${inter}/log"
-rescore=$inter/decode
+rescore="$inter/decode"
 
-[ `echo $inv_acoustic_scale | wc -w` -gt 1 ] && miac=true
-[ `echo $word_ins_penalty | wc -w` -gt 1 ] && mwip=true
+[ "$(echo "$inv_acoustic_scale" | wc -w)" -gt 1 ] && miac=true
+[ "$(echo "$word_ins_penalty" | wc -w)" -gt 1 ] && mwip=true
 
+#stop auto-exporting all variables
 set +a
 
-mkdir -p $inter
+mkdir -p $inter || die "unable to create intermediate directory $inter"
 timer="$(which time)" #This is not the shell's time function but GNU time! needs to be installed explicitly or you get weird errors!
 if [ -z "$timer" ]; then
-    echo "GNU time not found  (apt install time)">&2
-    exit 2
+    die "GNU time not found  (apt install time)"
 fi
-timer="$(which time) -o $inter/time.log -f \"%e %U %S %M\""
-cp "$0" "$inter/decode.sh" 	# Make a copy of this file and..
-echo "$0 $@" >$logging      # ..print the command line for logging
+timer="$timer -o $inter/time.log -f \"%e %U %S %M\""
+scriptname="$(dirname "$(readlink -f "$0")")" #the invoked script
+cp -f "$scriptname" "$inter/decode.sh" || die "error copying decode.sh ($scriptname)"		# Make a copy of this file and..
+echo "Command: $0 $*" | tee "$logging" >&2      # ..print the command line for logging
 
 ## data prep
 if [ $stage -le 3 ]; then
-	local/decode_prepdata.sh $@
+	local/decode_prepdata.sh "$@" || die "Data preparation failed"
 fi
 
 # determine maximum number of jobs for this feature generation and decoding
 numspeak=$(cat $data/ALL/spk2utt | wc -l)
-if (( $numspeak == 0 )); then echo "No speech found, exiting."; exit
-elif (( $nj > $numspeak )); then this_nj=$numspeak; echo "Number of speakers is less than $nj, reducing number of jobs to $this_nj"
+if (( numspeak == 0 )); then die "No speech found, exiting."
+elif (( nj > numspeak )); then this_nj=$numspeak; echo "Number of speakers is less than $nj, reducing number of jobs to $this_nj" >&2
 else this_nj=$nj
 fi
 
+
 ## feature generation
 if [ $stage -le 5 ]; then
-	echo "Feature generation" >$inter/stage
-	[ -e $model/mfcc.conf ] && cp $model/mfcc.conf $inter 2>/dev/null
-	[ -e $model/conf/mfcc.conf ] && cp $model/conf/mfcc.conf $inter 2>/dev/null
+	echo -e "\n==========================">&2
+	echo "Feature generation" | tee "$inter/stage" >&2
+	echo "==========================">&2
+	[ -e "$model/mfcc.conf" ] && cp "$model/mfcc.conf" "$inter" 2>/dev/null
+	[ -e "$model/conf/mfcc.conf" ] && cp "$model/conf/mfcc.conf" "$inter" 2>/dev/null
 **** INSERT FEATURES ****
 fi
 
 ## decode
-if [ $stage -le 7 ]; then
-	echo "Decoding" >$inter/stage
-	echo -n "Duration of speech: "
-	cat $data/ALL/segments | awk '{s+=$4-$3} END {printf("%.0f", s)}' | local/convert_time.sh
-	totallines=$(cat $data/ALL/segments | wc -l)
-	rm -r -f ${inter}/decode
+if [ $stage -le 6 ]; then
+	echo -e "\n==========================">&2
+	echo "Decoding" | tee "$inter/stage" >&2
+	echo "==========================">&2
+	echo -n "Duration of speech: " >&2
+	cat "$data/ALL/segments" | awk '{s+=$4-$3} END {printf("%.0f", s)}' | local/convert_time.sh
+	rm -r -f "${inter}/decode"
 **** INSERT DECODE ****
-	mv $inter/time.log $inter/time.decode.log
+	mv "$inter/time.log" "$inter/time.decode.log"
 fi
 
 ## rescore
-if [ $stage -le 9 ] && [ $llmodel ] && [ -e $inter/decode/num_jobs ]; then
-	echo "Rescoring" >$inter/stage
+if [ $stage -le 7 ] && [ -e "$lmodel" ] && [ -e "$inter/decode/num_jobs" ]; then
+	echo -e "\n==========================">&2
+	echo "Rescoring" | tee "$inter/stage" >&2
+	echo "==========================">&2
 	numjobs=$(< $inter/decode/num_jobs)
-	eval $timer steps/lmrescore_const_arpa.sh --skip-scoring true $lpath $llpath $data/ALL $inter/decode $inter/rescore >>$logging 2>&1 &
+	eval "$timer" steps/lmrescore_const_arpa.sh --skip-scoring true "$lpath" "$llpath" "$data/ALL" "$inter/decode" "$inter/rescore" | tee -a "$logging" 2>&1 &
 	pid=$!
 	spin='-\|/'
 	i=0
 	while kill -0 $pid 2>/dev/null; do
 		i=$(( (i+1) %4 ))
-  		printf "\rRescoring.. ${spin:$i:1}"
-  		sleep .2
+		printf "\rRescoring.. %s" "${spin:$i:1}"
+		sleep .2
 	done
-	cat $inter/time.log | awk '{printf("\rRescoring completed in %d:%02d:%02d (CPU: %d:%02d:%02d), Memory used: %d MB                \n", int($1/3600), int($1%3600/60), int($1%3600%60), int(($2+$3)/3600), int(($2+$3)%3600/60), int(($2+$3)%3600%60), $4/1000) }'
-	rescore=$inter/rescore
-	mv $inter/time.log $inter/time.rescore.log
+	cat "$inter/time.log"| awk '{printf("\rRescoring completed in %d:%02d:%02d (CPU: %d:%02d:%02d), Memory used: %d MB                \n", int($1/3600), int($1%3600/60), int($1%3600%60), int(($2+$3)/3600), int(($2+$3)%3600/60), int(($2+$3)%3600%60), $4/1000) }'
+	rescore="$inter/rescore"
 fi
 
-[ $llmodel ] && rescore=$inter/rescore
+[ -e "$lmodel" ] && rescore="$inter/rescore"
 
 if [ $splittext ]; then
 	splittext='-s'
@@ -182,18 +211,21 @@ else
 fi
 
 ## create readable output
-if [ $stage -le 11 ] && [ -e $rescore/num_jobs ]; then
-	echo -e "Producing output" >$inter/stage
+if [ $stage -le 8 ] && [ -e "$rescore/num_jobs" ]; then
+	echo -e "\n==========================">&2
+	echo -e "Producing output" | tee $inter/stage >&2
+	echo "==========================">&2
 
 	frame_shift_opt=
-	rm -f $data/ALL/1Best.* $result/1Best* $rescore/1Best.*
+	rm -f "$data"/ALL/1Best.* "$result"/1Best* "$rescore"/1Best.*
 
 	numjobs=$(< $rescore/num_jobs)
+	[ -z "$numjobs" ] && numjobs=1
 
-	if [ -f $model/frame_shift ]; then
-		frame_shift_opt="--frame-shift=$(cat $model/frame_shift)"
-	elif [ -f $model/frame_subsampling_factor ]; then
-		factor=$(cat $model/frame_subsampling_factor) || exit 1
+	if [ -f "$model/frame_shift" ]; then
+		frame_shift_opt="--frame-shift=$(cat "$model/frame_shift")"
+	elif [ -f "$model/frame_subsampling_factor" ]; then
+		factor=$(cat "$model/frame_subsampling_factor") || exit 1
 		frame_shift_opt="--frame-shift=0.0$factor"
 	fi
 
@@ -203,43 +235,104 @@ if [ $stage -le 11 ] && [ -e $rescore/num_jobs ]; then
 			ident=
 			[ $mwip ] && ident="$wip."
 			[ $miac ] && ident="$ident$iac."
-			$cmd --max-jobs-run $nj JOB=1:$numjobs $inter/l2c_log/lat2ctm.${ident}JOB.log \
+			$cmd --max-jobs-run $nj "JOB=1:$numjobs" "$inter/l2c_log/lat2ctm.${ident}JOB.log" \
 				gunzip -c $rescore/lat.JOB.gz \| \
 				lattice-push ark:- ark:- \| \
 				lattice-add-penalty --word-ins-penalty=$wip ark:- ark:- \| \
-				lattice-align-words $wordbound $model/final.mdl ark:- ark:- \| \
-				lattice-to-ctm-conf $frame_shift_opt --inv-acoustic-scale=$iac ark:- - \| utils/int2sym.pl -f 5 $symtab \| \
+				lattice-align-words "$wordbound" "$model/final.mdl" ark:- ark:- \| \
+				lattice-to-ctm-conf "$frame_shift_opt" --inv-acoustic-scale=$iac ark:- - \| utils/int2sym.pl -f 5 "$symtab" \| \
 				local/ctm_time_correct.pl $data/ALL/segments \| sort \> $rescore/1Best.${ident}JOB.ctm | exit 1;
-			cat $rescore/1Best.${ident}*.ctm >$rescore/1Best_raw.${ident}ctm
+			cat $rescore/1Best.${ident}*.ctm >$rescore/1Best_raw.${ident}ctm || die "Command produced no viable output: $cmd"
 
 			cat $rescore/1Best_raw.${ident}ctm | sort -k1,1 -k3,3n | local/remove_hyphens.pl | \
 				perl local/combine_numbers.pl | sort -k1,1 -k3,3n | local/compound-restoration.pl 2>>$logging | \
-				grep -E --text -v 'uh|<unk>' >$result/1Best.${ident}ctm
+				grep -E --text -v 'uh|<unk>' >$result/1Best.${ident}ctm || die "Postprocesing raw CTM into final CTM failed"
+            [ ! -e "$result/1Best.${ident}ctm" ] && die "Failed to generate expected output $result/1Best.${ident}ctm"
 			[ -s $data/ALL/all.glm ] && mv $result/1Best.${ident}ctm $rescore/1Best_prefilt.${ident}ctm && \
-				cat $rescore/1Best_prefilt.${ident}ctm | csrfilt.sh -s -i ctm -t hyp $data/ALL/all.glm >$result/1Best.${ident}ctm
+                (cat $rescore/1Best_prefilt.${ident}ctm | csrfilt.sh -s -i ctm -t hyp "$data/ALL/all.glm" >"$result/1Best.${ident}ctm" 2>&1 | tee -a $logging >&2 || die "Filtering 1Best.ctm failed (csrfilt.sh)")
 
-			[ $ident ] && ident="-i '$ident'"
-			local/Create_JSON.py -t $json $splittext $ident $result
+			local/Create_JSON.py -t "$json" "$splittext" "$ident" "$result" 2>&1 | tee -a $logging >&2|| die "Create_JSON failed"
 		done
 	done
 fi
 
 ## score if reference transcription exists
-if [ $stage -le 13 ] && [ -s $data/ALL/ref.stm ]; then
-	echo -e "Scoring" >$inter/stage
+if [ $stage -le 9 ] && [ -s "$data/ALL/ref.stm" ]; then
+	echo -e "\n==========================">&2
+	echo -e "Scoring" | tee $inter/stage >&2
+	echo "==========================">&2
 	# score using asclite, then produce alignments and reports using sclite
-	[ -s $data/ALL/test.uem ] && uem="-uem $data/ALL/test.uem"
+	[ -s "$data/ALL/test.uem" ] && uem="-uem $data/ALL/test.uem"
 	for iac in $inv_acoustic_scale; do
 		for wip in $word_ins_penalty; do
 			ident=
 			[ $mwip ] && ident="$wip."
 			[ $miac ] && ident="$ident$iac."
-			asclite -D -noisg -r $data/ALL/ref.stm stm -h $result/1Best.${ident}ctm ctm $uem -o sgml >>$logging 2>&1
-			cat $result/1Best.${ident}ctm.sgml | sclite -P -o sum -o pralign -o dtl -n $result/1Best.${ident}ctm  >>$logging 2>&1
-			[ $(cat $result/1Best.${ident}ctm.sys | grep 'MS\|FS\|MT\|FT' | wc -l) -gt 0 ] && local/split_results.sh $result/1Best.${ident}ctm.sys $result/1Best.${ident}ctm.sys.split
+			asclite -D -noisg -r "$data/ALL/ref.stm" stm -h "$result/1Best.${ident}ctm" ctm "$uem" -o sgml 2>&1 | tee -a "$logging" >&2
+			cat "$result/1Best.${ident}ctm.sgml" | sclite -P -o sum -o pralign -o dtl -n $result/1Best.${ident}ctm 2>&1  | tee -a "$logging" >&2
+			[ -e "$result/1Best.${ident}ctm.sys" ] && [ "$(cat "$result/1Best.${ident}ctm.sys" | grep -c 'MS\|FS\|MT\|FT')" -gt 0 ] && local/split_results.sh "$result/1Best.${ident}ctm.sys" "$result/1Best.${ident}ctm.sys.split"
+		done
+	done
+
+	#add an output variant without the scores
+	for iac in $inv_acoustic_scale; do
+		for wip in $word_ins_penalty; do
+			ident=
+			[ $mwip ] && ident="$wip."
+			[ $miac ] && ident="$ident$iac."
+			cat $result/1Best.${ident}txt | cut -d'(' -f 1 > $inter/1Best_plain.${ident}txt
 		done
 	done
 fi
 
-echo -e "Done" >$inter/stage
-echo "Done"
+if [ -z "$mwip" ] && [ -z "$miac" ]; then
+	#these parts of the pipeline only work when idents are not used (mwip/miac are unset)
+
+	if [ ! -f "$result/1Best.ctm" ]; then
+		die "Expected output file $result/1Best.ctm not found after decoding!"
+	fi
+
+	## convert to XML if output exists
+	if [ $stage -le 10 ] && [ -s "$result/1Best.ctm" ] && [ -x ./scripts/ctm2xml.py ];
+	then
+		echo -e "\n==========================">&2
+		echo -e "Conversion to XML" | tee $inter/stage >&2
+		echo "==========================">&2
+
+		./scripts/ctm2xml.py "$result" "1Best" "$inter" || die "ctm2xml failed"
+	fi
+
+	## process speaker diarisation output
+	if [ $stage -le 11 ] && [ -s "$result/liumlog/1Best.seg" ] && [ -x ./scripts/addspkctm.py ];
+	then
+		echo -e "\n==========================">&2
+		echo -e "Processing speaker diarisation output" | tee $inter/stage >&2
+		echo "==========================">&2
+
+		#note, idents (mwip/miac are not for pipelines that use this and late stages
+
+		# Create .rttm
+		spkr_seg="$result/liumlog/1Best.seg"
+		cat "$spkr_seg" | sed -n '/;;/!p' | sort -nk3 | awk '{printf "SPEAKER %s %s %.2f %.2f <NA> <NA> %s <NA>\n", $1, $2, ($3 / 100), ($4 / 100), $8}' > "$result/1Best.rttm" || die "Failure creating RTTM file from speaker diarisation output"
+
+		# Create .ctm with speaker ids
+		./scripts/addspkctm.py "$result/1Best.rttm" "$result/1Best.ctm" || die "Failure adding speakers to CTM"
+	fi
+
+	if [ $stage -le 12 ] && [ -s "$result/liumlog/1Best.seg" ] && [ -x ./scripts/wordpausestatistic.perl ]; then
+		echo -e "\n==========================">&2
+		echo -e "Adding sentence boundaries" | tee $inter/stage >&2
+		echo "==========================">&2
+
+		# Add sentence boundaries
+		cat "$result/1Best.ctm" | perl scripts/wordpausestatistic.perl 1.0 "$result/1Best.sent" || die "Failure adding sentence boundaries"
+	fi
+
+fi
+
+echo "Output written to:">&2
+echo " - CTM:                 $result/1Best.ctm">&2
+echo " - Text with scores:    $result/1Best.txt">&2
+echo " - Text without scores: $result/1Best_plain.txt" >&2
+echo " - XML:                 $result/1Best.xml" >&2
+echo "Done" | tee $inter/stage >&2
