fixed calls to data preperation and feature generation

diff --git a/local/decode_template b/local/decode_template
--- a/local/decode_template
+++ b/local/decode_template
@@ -144,16 +144,17 @@ fi
 if [[ "$result" = *" "* ]]; then
 	die "Output path ($result) may not contain any spaces!"
 fi
-inter="${result}/intermediate"
-data="${inter}/data"
-logging="${inter}/log"
-rescore="$inter/decode"
 
 [ "$(echo "$inv_acoustic_scale" | wc -w)" -gt 1 ] && miac=true
 [ "$(echo "$word_ins_penalty" | wc -w)" -gt 1 ] && mwip=true
 
 #stop auto-exporting all variables
 set +a
+
+inter="${result}/intermediate"
+data="${inter}/data"
+logging="${inter}/log"
+rescore="$inter/decode"
 
 mkdir -p $inter || die "unable to create intermediate directory $inter"
 timer="$(which time)" #This is not the shell's time function but GNU time! needs to be installed explicitly or you get weird errors!
@@ -168,7 +169,7 @@ echo "Command: $0 $*" | tee "$logging" >&2      # ..print the command line for l
 ## data prep
 if [ $stage -le 3 ]; then
 	logtitle "Data Preparation"
-	local/decode_prepdata.sh "$@" || die "Data preparation failed"
+	source local/decode_prepdata.sh || die "Data preparation failed"
 fi
 
 # determine maximum number of jobs for this feature generation and decoding
